serial_cheker/serial_cheker/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from serial_cheker import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('serials.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serial_cheker/serials/urls.py
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('', views.SerialList.as_view(), name='home-page'),
    path('top_10/', views.Top10View.as_view(), name='top-10'),
    path('adding/', views.AddingTvShows.as_view(), name='add-page'),
    path('registration/', views.Registration.as_view(), name='registration'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('genres/', views.GenresView.as_view()),
    path('<slug:serial_slug>/series/', views.SerieView.as_view(), name='episode'),
    path('<slug:serial_slug>/series/create/', views.SerieCreate.as_view()),
    path('<slug:serial_slug>/series/<slug:slug>/update/', views.SerieUpdate.as_view()),
    path('<slug:serial_slug>/series/<slug:slug>/delete/', views.SerieDelete.as_view()),
    path('<slug:serial_slug>/series/filter/', views.EpisodeFilter.as_view(), name="movie-filter"),
    path('<slug:serial_slug>/series/create/', views.SerieCreate.as_view()),
    path('genres/<int:genre_id>/', views.SerialByGenres.as_view(), name='filter-genres'),
    path('<slug:slug_title>/', views.PageViews.as_view(), name='page-view'),
]

serial_cheker/serials/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

# Create your models here.
from django.urls import reverse
from pytils.translit import slugify


class Platforms(models.Model):
    platform = models.CharField(
        max_length=255)
    slug = models.SlugField(
        max_length=255)

    def __str__(self):
        return self.platform


class Genres(MPTTModel):
    name = models.CharField(max_length=100)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    slug = models.SlugField(
        max_length=255, null=True, blank=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('filter-genres', args=[self.pk])


class Serials(models.Model):
    title = models.CharField(
        max_length=255)
    details = models.TextField()
    rating = models.IntegerField(
        validators=[MaxValueValidator(10),
                    MinValueValidator(1)])
    platform = models.ForeignKey(
        Platforms,
        on_delete=models.CASCADE)
    budget = models.IntegerField(
        validators=[MinValueValidator(1)],
        blank=True,
        null=True)
    box_office = models.IntegerField(
        validators=[MinValueValidator(1)],
        blank=True,
        null=True)
    slug = models.SlugField(
        max_length=255,)
    main_image = models.FileField(upload_to='media', default='No image')
    genre = models.ForeignKey(Genres, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('page-view', args=[self.slug])


class ImagesSerial(models.Model):
    photos = models.ImageField()
    serial = models.ForeignKey(Serials, on_delete=models.CASCADE, related_name='serials', null=True, blank=True)


class Series(models.Model):
    image = models.ImageField()
    serial = models.ForeignKey(Serials, on_delete=models.CASCADE, related_name='episode', null=True, blank=True)
    title = models.CharField(max_length=255)
    details = models.TextField()
    episode_rating = models.IntegerField(
        validators=[MaxValueValidator(10),
                    MinValueValidator(1)])
    slug = models.SlugField(
        max_length=255)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('episode', kwargs={'serial_slug': self.serial.slug})


class Comment(MPTTModel):
    username = models.CharField(max_length=150)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    email = models.EmailField(blank=True)
    comment = models.TextField()
    rating = models.IntegerField(validators=[MaxValueValidator(10), MinValueValidator(1)])
    serial = models.ForeignKey(Serials, on_delete=models.CASCADE, related_name='comment')
    publish = models.DateTimeField(auto_now_add=True)

    class MPTTMeta:
        order_insertion_by = ['publish']

    def __str__(self):
        return f'{self.username}||{self.email} - {self.comment}||{self.rating}'

serial_cheker/serials/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV3
from django.core.exceptions import ValidationError
from mptt.forms import TreeNodeChoiceField

from .models import *
from django import forms


class AddingTvShow(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['platform'].empty_label = 'Канал не выбран'
        self.fields['genre'].empty_label = 'Канал не выбран'

    class Meta:
        model = Serials
        fields = ['title', 'rating', 'genre', 'details', 'platform', 'main_image', ]
        labels = {
            'title': 'Название',
            'rating': 'Рейтинг',
            'details': 'Описание',
            'main_image': "Добавить фотографию",
            'platform': 'Канал',
            'genre': 'Жанр'
        }


class AddingSerie(forms.ModelForm):

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 40:
            raise ValidationError('Длина названия превышает 40 символов')
        return title

    def clean_details(self):
        details = self.cleaned_data['details']
        if len(details) < 10:
            raise ValidationError('Минимальная длина отзыва 10 символов')
        return details

    class Meta:
        model = Series
        fields = ['title', 'details', 'image', 'episode_rating']
        labels = {
            'title': 'Название',
            'episode_rating': 'Рейтинг',
            'details': 'Описание',
            'image': "Добавить фотографию",
        }

        error_messages = {'episode_rating':
            {
                'max_value': 'Максимальное значение Рейтнга - 10',
                'min_value': 'Максимальное значение Рейтнга - 10'
            },
            'title': {
                'required': 'Данное поле обязательно к заполнению'
            },
        }


class AddingPhoto(forms.ModelForm):
    class Meta:
        model = ImagesSerial
        fields = ['photos']


class CommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parent'].widget.attrs.update({'class': 'd-none'})
        self.fields['parent'].required = False
        self.fields['parent'].label = ''

    class Meta:
        model = Comment
        fields = ['username', 'email', 'comment', 'parent', 'rating']
        labels = {
            'username': 'Имя Пользователя:',
            'email': 'Почтовый ящик:',
            'comment': 'Отзыв:',
            'rating': "Рейтинг:",
        }


class UserRegistration(UserCreationForm):
    username = forms.CharField(
        label='Имя Пользователя',
        widget=forms.TextInput(attrs={'cols': 40, 'row': 10}))
    email = forms.EmailField(
        label='Почта',
        widget=forms.EmailInput(attrs={'cols': 40, 'row': 10}))
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'cols': 40, 'row': 10}))
    password2 = forms.CharField(
        label='Подтверждение пароля',
        widget=forms.PasswordInput(attrs={'cols': 40, 'row': 10}))
    captcha = ReCaptchaField(widget=ReCaptchaV3(attrs={'required_score': 0.85, }))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class Login(AuthenticationForm):
    username = forms.CharField(
        label='Имя Пользователя',
        widget=forms.TextInput(attrs={'cols': 40, 'row': 10}))
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'cols': 40, 'row': 10}))

serial_cheker/serials/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView
from django.db.models import Avg, Q, Count
from django.forms import modelformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404

# Create your views here.
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import *
from .models import *
from .utils import DataMixin


class SerialList(DataMixin, ListView):
    model = Serials
    template_name = 'serials/list_of_serials.html'
    context_object_name = 'serials'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        genres = Genres.objects.all()
        c_def = self.get_user_context(title='Главная страница', genres=genres)
        return context | c_def

    def get_queryset(self):
        return Serials.objects.order_by('pk').select_related('platform').prefetch_related('serials')


class PageViews(DataMixin, View):

    def get(self, request, slug_title):
        form = CommentForm()
        tv_show = Serials.objects.get(slug=slug_title)
        avg = tv_show.comment.all().aggregate(Avg('rating'))
        comments = Comment.objects.filter(serial_id=tv_show.pk)
        context = self.get_user_context(form=form, serial=tv_show, comments=comments, avg=avg['rating__avg'],)
        return render(request, 'serials/serial_page.html', context=context)

    def post(self, request, slug_title):
        form = CommentForm(request.POST)
        tv_show = Serials.objects.get(slug=slug_title)
        current_page = reverse_lazy('page-view', args=[slug_title])
        if form.is_valid():
            obj = form.save(commit=False)
            obj.serial_id = tv_show.pk
            obj.save()
            return redirect(current_page)
        comments = Comment.objects.filter(serial_id=tv_show.pk)
        context = self.get_user_context(form=form, serial=tv_show, comments=comments)
        return render(request, 'serials/serial_page.html', context=context)


class GenresView(ListView):
    model = Genres
    template_name = 'includes/genres.html'
    context_object_name = 'genres'


class SerialByGenres(DataMixin, ListView):
    model = Serials
    template_name = 'serials/genre.html'
    context_object_name = 'genre'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        genres = Genres.objects.all()
        c_def = self.get_user_context(title='Топ десять', genres=genres)
        return context | c_def

    def get_queryset(self):
        return Serials.objects.filter(Q(genre_id=self.kwargs['genre_id']))


class Top10View(DataMixin, ListView):
    model = Serials
    template_name = 'serials/top_10.html'
    context_object_name = 'serials'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Топ десять')
        return context | c_def

    def get_queryset(self):
        return Serials.objects.order_by('-rating')[:5]


class AddingTvShows(DataMixin, CreateView):
    form_class = AddingTvShow
    template_name = 'serials/adding.html'
    success_url = reverse_lazy('home-page')
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Добавте сериал')
        return context | c_def


class SerieView(DataMixin, ListView):
    model = Series
    template_name = 'serials/serie.html'
    context_object_name = 'serie'
    paginate_by = 5

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        tv_show = Serials.objects.get(slug=self.kwargs['serial_slug'])
        rating = Series.objects.values('episode_rating').annotate(Count('pk')).filter(serial__slug=self.kwargs['serial_slug'])
        serial_title = Series.objects.values('title').distinct().filter(serial__slug=self.kwargs['serial_slug'])
        c_def = self.get_user_context(title='Серия Сериала', rating=rating, serial_title=serial_title, tv_show=tv_show)
        return context | c_def

    def get_queryset(self):
        get_object_or_404(Serials, slug=self.kwargs['serial_slug'])
        return Series.objects.filter(serial__slug=self.kwargs['serial_slug']).select_related('serial')


class SerieUpdate(DataMixin, UpdateView):
    model = Series
    template_name = 'serials/serie_update.html'
    fields = ['title', 'episode_rating', 'details', 'image',]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Изменение')
        return context | c_def

    def get_queryset(self):
        return Series.objects.filter(serial__slug=self.kwargs['serial_slug'])

    def get_success_url(self):
        return reverse_lazy('episode', kwargs={'serial_slug': self.kwargs['serial_slug']})


class SerieDelete(DataMixin, DeleteView):
    model = Series
    template_name = 'serials/serie_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Удаление')
        return context | c_def

    def get_queryset(self):
        return Series.objects.filter(serial__slug=self.kwargs['serial_slug'])

    def get_success_url(self):
        return reverse_lazy('episode', kwargs={'serial_slug': self.kwargs['serial_slug']})



class SerieCreate(DataMixin, CreateView):
    form_class = AddingSerie
    template_name = 'serials/serie_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Добавте серию')
        return context | c_def

    def get_queryset(self):
        return Series.objects.filter(serial__slug=self.kwargs['serial_slug'])

    def form_valid(self, form):
        serial = form.save(commit=False)
        serial.serial = Serials.objects.get(slug=self.kwargs['serial_slug'])
        serial.save()
        series_page = reverse_lazy('episode', kwargs={'serial_slug': self.kwargs['serial_slug']})
        return redirect(series_page)


class EpisodeFilter(SerieView):

    def get_queryset(self):
        if 'episode_rating' in self.request.GET and 'title' in self.request.GET:
            return Series.objects.filter(episode_rating__in=self.request.GET.getlist('episode_rating'),
                                         title__in=self.request.GET.getlist('title'),
                                         serial__slug=self.kwargs['serial_slug'])
        elif 'episode_rating' in self.request.GET:
            return Series.objects.filter(episode_rating__in=self.request.GET.getlist('episode_rating'),
                                         serial__slug=self.kwargs['serial_slug'])
        elif 'title' in self.request.GET:
            return Series.objects.filter(title__in=self.request.GET.getlist('title'),
                                         serial__slug=self.kwargs['serial_slug'])
        else:
            return Series.objects.filter(serial__slug=self.kwargs['serial_slug']).select_related('serial')


class Registration(DataMixin, CreateView):
    form_class = UserRegistration
    template_name = 'serials/registration.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Регистрация')
        return context | c_def

    def form_valid(self, form):
        new_user = form.save()
        login(self.request, new_user)
        return redirect('home-page')


class UserLogin(DataMixin, LoginView):
    form_class = Login
    template_name = 'serials/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Вход')
        return context | c_def

    def get_success_url(self):
        return reverse_lazy('home-page')


def logout_user(request):
    logout(request)
    return redirect('home-page')

serial_cheker/serials/templates/serials/adding.html
{% extends 'serials\base.html'%}


{% block content %}

<div class="container_form_adding">
<form method="post" action="{% url 'add-page' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
    <div>{{form.non_field_errors}}</div>
    {% for f in form %}
    <p class="text-center"><label for="{{f.id_for_label}}" class="label_login">{{f.label}}</label><br> {{f}}</p>
    {% endfor %}
    </div>
    <div>{{f.errors}}</div>
    <button type="submit" class="btn btn-outline-warning label_login">Добавить</button>
</form>
</div>


{% endblock %}

serial_cheker/serials/templates/serials/base.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link rel="shortcut icon" href="image/film-strip-roll-movie-retro_108506.ico" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'serials/css/styles.css' %}">
</head>
<body>
<header>
<div class="username">
<h3>{%for position in menu%}
    <a href="{% url position.url  %}">{{position.name}}</a>
    {%endfor%}
    <label>{%if request.user.is_authenticated%}
        {{user.username}} | <a href="{% url 'logout' %}">Выход </a></h3>
    {% else %}
    <a href="{% url 'registration' %}">Регистрация</a> |
    <a href="{% url 'login' %}">Вход </a></h3>
    {% endif %}</label>
</div>
</header>


{% block content %}{% endblock %}



<div class="paginator">
    <ul>
        {% if page_obj.has_previous%}
        <li class="switch">
            <a href="?page={{page_obj.previous_page_number}}"><</a>
        </li>
        {%endif%}

        {% for p in paginator.page_range%}
        {% if p == page_obj.number %}
        <li class="current">
            {{p}}
        </li>
        {% elif p <= page_obj.number|add:3 and p >= page_obj.number|add:-3 %}
        <li class="other">
            <a href="?page={{p}}">{{p}}</a>
        </li>
        {% endif %}
        {%endfor%}

        {%if page_obj.has_next%}
        <li class="switch">
            <a href="?page={{page_obj.next_page_number}}">></a>
        </li>
        {%endif%}
    </ul>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>

</body>
</html>

serial_cheker/serials/templates/serials/genre.html
{% extends 'serials\base.html'%}

{%block content%}
<div class="genres">
<h3>Жанры сериалов</h3>
{% include "includes/genres.html" %}</div>
<ul>{% for f in genre %}
    <div class="serial-list-genre">
    <li>
        <img src="{{f.main_image.url}}">
        <br>
            <a href="{{f.get_absolute_url}}">
        {{f.title}}
    </a>
    </li>
    </div>
{%endfor%}
</ul>{%endblock%}

serial_cheker/serials/templates/serials/list_of_serials.html
{% extends 'serials\base.html'%}


{% block content %}

<div class="genres">
<h4>Жанры сериалов</h4>
{% include "includes/genres.html" %}</div>

<div class="container">
  <div class="row">
        {% for f in serials %}
      <div class="col serial-list">
    {% if f.main_image != 'No image'%}
    <img src="{{f.main_image.url}}">
    {%endif%}
    <a href="{{f.get_absolute_url}}">
        {{f.title}} | {{f.platform}}
    </a>
    </div>
        {%endfor%}
  </div>
</div>

{% endblock %}

serial_cheker/serials/templates/serials/login.html
{% extends 'serials\base.html'%}

{%block content%}
<div class="container_form">
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
    <div>{{form.non_field_errors}}</div>
    {% for f in form %}
    <p class="text-center"><label for="{{f.id_for_label}}" class="label_login">{{f.label}}</label><br> {{f}}</p>
    {% endfor %}
    </div>
    <div>{{f.errors}}</div>
    <button type="submit" class="btn btn-outline-warning label_login">Авторизация</button>
</form>
</div>


{%endblock%}

serial_cheker/serials/templates/serials/registration.html
{% extends 'serials\base.html'%}
{%block content%}
<div class="container_form">
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
    <div>{{form.non_field_errors}}</div>
    {% for f in form %}
    <p class="text-center"><label for="{{f.id_for_label}}" class="label_login">{{f.label}}</label><br> {{f}}</p>
    {% endfor %}
    </div>
    <div>{{f.errors}}</div>
    <button type="submit" class="btn btn-outline-warning label_login">Регистрация</button>
</form>
</div>
{%endblock%}

serial_cheker/serials/templates/serials/serial_page.html
{% extends 'serials\base.html'%}


{% block content %}
<div class="serial-page">
<style>
        .children form{
                margin-left: -48px;
        }

        .children .children form{
                margin-left: -96px;
        }
</style>

<div class="serial-info">
<h1>{{serial.title}}</h1>
<h2>{{serial.platform|upper}}</h2>
<h3>Author Rating: {{serial.rating}} || User Rating:
{% if avg %}{{avg|floatformat:2}}{%else%}No Rating Yet{%endif%}</h3>

        <a href="{{serial.get_absolute_url}}series">Список Эпизодов</a>

{% if serial.main_image != 'No image'%}
<img src="{{serial.main_image.url}}" class="serial_image">
{%else%}
<h3>No Image</h3>
{%endif%}
<h4>{{serial.details}}</h4>
</div>



<div class="comment-form">
<form method="post">
{% csrf_token%}
<div>{{form.non_field_errors}}</div>
{% for f in form%}
<div class="error">{{f.errors}}</div>
<div class="form-group">
<label for="{{f.id_for_label}}">{{f.label}}</label>{{f}}
</div>
{% endfor %}
<button type="submit" class="btn">Добавить свой комментарий</button>
</form>
</div>


{% load mptt_tags %}
<div>
{%if comments%}
{% recursetree comments %}
<div id="{{node.id}}" class="my-2 p-2" style="border: 4px solid #DFB63F">
<div class="d-flex justify-content-between">By {{node.username}} <div>{{node.publish}}</div>
        </div>
<div>My Rating: {{node.rating}}</div>
        <hr>
<div>{{node.comment}}
{% if node.level < 3%}
<button class="button float-md-end" onclick="myFunction({{node.id}})">Reply</button>
{%endif%}
</div>
</div>
{%if not node.is_leaf_node%}
        <div class="children ms-5"> {{children}}</div>
{%endif%}
{%endrecursetree%}
{%else%}
<h4 class="text-center">Твой комментарий может стать первым!</h4>
{%endif%}
</div>


<script>

      function formExit() {
      document.getElementById("newForm").remove();
      }

      function myFunction(id)   {

      if (document.contains(document.getElementById("newForm"))) {
        document.getElementByID("newForm").remove();
      }

      var a = document.getElementById(id);
      a.insertAdjacentHTML('afterend',
      '<form id="newForm" class="form-insert py-2" method="post"> \
      <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Close</button></div></div> \
      <label for="id_name">Name:</label> \
      <input type="text" name="username" class="col-sm-12" maxlength="100" required="" id="id_name">\
      <select name="parent" class="d-none" id="id_parent"> \
      <option value="' + id + '" selected="' + id + '"></option> \
      </select> \
      <label for="id_email">Email:</label> \
      <input type="text" name="email" class="col-sm-12" maxlength="254" required="" id="id_email"> \
      <label for="id_content">Content:</label> \
      <textarea name="comment" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
      <label for="id_rating">Rating:</label> \
      <input type="integer" name="rating" class="col-sm-12" maxvalue=10 required="" id="id_rating"> \
      {% csrf_token %} \
      <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button> \
      </form>');
}

</script>
{% endblock %}





{%comment%}
{%if comments%}
{% for comment in comments%}
<div class="comment">
{{comment.username}} ({{comment.email}})
Rating: {{comment.rating}}/10
        <br>
<label>{{comment.comment}}</label>
</div>
{%endfor%}
{%else%}
<label>No Comments Yet, you can be first!</label>
{%endif%}
</div>
{%endcomment%}

serial_cheker/serials/templates/serials/serie.html
{% extends 'serials/base.html'%}


{% block content %}
<div class="genres mr-5">
<form action="{%url 'movie-filter' tv_show.slug %}" method="get">
    {%if rating%}
    <h4>Фильтр по рейтингу</h4>
    <ul>
      {% for f in rating %}
      <li>
        <input type="checkbox" name="episode_rating" value="{{f.episode_rating}}">
        <span>{{f.episode_rating}}</span>
      </li>
      {%endfor%}
    </ul>
    {%endif%}
    {%if serial_title%}
    <h4>Фильтр по имени</h4>
    <ul>
      {% for f in serial_title %}
      <li>
        <input type="checkbox" name="title" value="{{f.title}}">
        <span>{{f.title}}</span>
      </li>
      {%endfor%}
    </ul>
    <button type="submit">Найти</button>
    {%else%}
    <h4>Ни одна серия не добавлена!</h4>
    {%endif%}
</form>
</div>
<div class="container">
{% if serials.views.EpisodeFilter %} b
<a class="btn btn-warning" href="{{form.get_absolute_url}}create/" role="button">Створити</a>
{%endif%}
<div class="container-form">
  {% for f in serie %}
  <div class="row gx=2 mb-3 align-items-center" style="border: 4px solid #DFB63F">

    <div class="col text-center">
    {{f.title}}
    </div>

    <div class="col text-center">
    <img height="126" width="240"  class="img-thumbnail img-fluid" src="{{f.image.url}}">
    </div>

    <div class="col text-center">
    {{f.episode_rating}}
    </div>

    <div class="col text-center">
    {{f.details}}
    </div>

    <div class="col text-center">
          <a href="{{f.get_absolute_url}}{{f.slug}}/delete/" class="btn btn-warning" role="button">Видатили</a> <br>
          <a href="{{f.get_absolute_url}}{{f.slug}}/update/" class="btn btn-warning" role="button">Оновити</a>
    </div>

    </div>
    {%endfor%}
</div>
</div>


{% endblock %}

serial_cheker/serials/templates/serials/serie_create.html
{% extends 'serials\base.html'%}


{% block content %}

<div class="container_form">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
    <div>{{form.non_field_errors}}</div>
    {% for f in form %}
    <p class="text-center"><label for="{{f.id_for_label}}" class="label_login">{{f.label}}</label><br> {{f}}</p>
    <div>{{f.errors}}</div>
    {% endfor %}
    </div>
    <button type="submit" class="btn btn-outline-warning label_login">Записать серию</button>
</form>
</div>

{%endblock%}